#!/usr/bin/env python
"""Sensitivity and robustness checks for the Neurospora phenome-architecture analysis.

This script adds three robustness checks:

1. Discretization sensitivity for continuous phenotype assays.
2. Gene-class annotation quality control and mode-stability analysis.
3. Metabolic-model contrast analysis.

All paths are resolved from --project-root. The script expects the base project
outputs generated by scripts/prepare_phenotype_matrix.py and can optionally
reuse the architecture workbook generated by scripts/analyze_functional_architecture.py.
"""

from __future__ import annotations

import argparse
import itertools
import math
import re
import warnings
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy import stats

NORMAL_VALUES = {"normal", "normal_range", "normal range", "wild_type", "wild-type", "wt"}
NCU_RE = re.compile(r"NCU\d{5}", flags=re.IGNORECASE)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run sensitivity and robustness checks for the Neurospora phenome-architecture project.")
    p.add_argument("--project-root", default=".", help="Project root")
    p.add_argument("--random-set-iterations", type=int, default=2000, help="Random gene-set iterations for metabolic contrast nulls")
    p.add_argument("--random-seed", type=int, default=20260601)
    p.add_argument("--min-class-size", type=int, default=5)
    p.add_argument("--output-workbook", default="", help="Optional output workbook path")
    return p.parse_args()


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def first_existing(paths: Sequence[Path]) -> Optional[Path]:
    for path in paths:
        if path.exists():
            return path
    return None


def find_file(root: Path, preferred: Sequence[Path], patterns: Sequence[str]) -> Optional[Path]:
    hit = first_existing(preferred)
    if hit is not None:
        return hit
    for pattern in patterns:
        hits = sorted(root.glob(pattern))
        if hits:
            return hits[0]
    return None


def read_csv_required(path: Optional[Path], label: str) -> pd.DataFrame:
    if path is None or not path.exists():
        raise FileNotFoundError(f"Could not find {label}. Run scripts/prepare_phenotype_matrix.py first.")
    return pd.read_csv(path)


def canonical_bool(s: pd.Series) -> pd.Series:
    if s.dtype == bool:
        return s.fillna(False)
    return s.astype(str).str.strip().str.lower().isin({"true", "1", "yes", "y", "t"})


def bh_fdr(pvals: Sequence[float]) -> np.ndarray:
    p = np.asarray([1.0 if pd.isna(x) else float(x) for x in pvals], dtype=float)
    n = len(p)
    if n == 0:
        return np.array([])
    order = np.argsort(p)
    ranks = np.empty(n, dtype=int)
    ranks[order] = np.arange(1, n + 1)
    q = p * n / ranks
    q_sorted = q[order]
    q_sorted = np.minimum.accumulate(q_sorted[::-1])[::-1]
    out = np.empty(n, dtype=float)
    out[order] = np.minimum(q_sorted, 1.0)
    return out


def safe_fisher(a: int, b: int, c: int, d: int) -> Tuple[float, float]:
    try:
        odds, p = stats.fisher_exact([[a, b], [c, d]])
        return float(odds), float(p)
    except Exception:
        return np.nan, np.nan


def log2_or_corrected(a: int, b: int, c: int, d: int) -> float:
    return float(np.log2(((a + 0.5) * (d + 0.5)) / ((b + 0.5) * (c + 0.5))))


def assay_axis(assay: str) -> str:
    low = assay.lower()
    if "basal" in low or "aerial" in low or "hypha" in low:
        return "growth"
    if "conidia" in low:
        return "asexual_development"
    if "protoperithe" in low or "perithe" in low or "ascospore" in low:
        return "sexual_development"
    return "other"


def normalize_category(series: pd.Series) -> pd.Series:
    return series.astype("string").str.strip().str.replace(r"\s+", "_", regex=True).str.lower().fillna("missing")


def quantile_label(x: pd.Series, probs: Sequence[float], labels: Sequence[str]) -> pd.Series:
    vals = pd.to_numeric(x, errors="coerce")
    if vals.notna().sum() < 5 or vals.nunique(dropna=True) <= 3:
        return vals.astype("string").fillna("missing")
    qs = vals.quantile(probs).to_numpy(dtype=float)
    # Prevent duplicate cut points from crashing; ties are common in phenotype tables.
    qs = np.maximum.accumulate(qs)
    out = []
    for v in vals:
        if pd.isna(v):
            out.append("missing")
            continue
        j = int(np.searchsorted(qs, float(v), side="right"))
        j = min(j, len(labels) - 1)
        out.append(labels[j])
    return pd.Series(out, index=x.index, dtype="string")


def qcut_label(x: pd.Series, q: int, prefix: str) -> pd.Series:
    vals = pd.to_numeric(x, errors="coerce")
    if vals.notna().sum() < 5 or vals.nunique(dropna=True) <= 3:
        return vals.astype("string").fillna("missing")
    try:
        codes = pd.qcut(vals.rank(method="first"), q=q, labels=False, duplicates="drop")
    except Exception:
        codes = pd.Series(np.zeros(len(vals), dtype=int), index=x.index)
    return codes.map(lambda z: "missing" if pd.isna(z) else f"{prefix}{int(z) + 1}").astype("string")


def equal_width_label(x: pd.Series, bins: int) -> pd.Series:
    vals = pd.to_numeric(x, errors="coerce")
    if vals.notna().sum() < 5 or vals.nunique(dropna=True) <= 3:
        return vals.astype("string").fillna("missing")
    try:
        codes = pd.cut(vals, bins=bins, labels=False, include_lowest=True)
    except Exception:
        codes = pd.Series(np.zeros(len(vals), dtype=int), index=x.index)
    return codes.map(lambda z: "missing" if pd.isna(z) else f"eq{int(z) + 1}").astype("string")


def zscore_label(x: pd.Series) -> pd.Series:
    vals = pd.to_numeric(x, errors="coerce")
    mu = vals.mean()
    sd = vals.std(ddof=1)
    if vals.notna().sum() < 5 or not np.isfinite(sd) or sd == 0:
        return vals.astype("string").fillna("missing")
    z = (vals - mu) / sd
    labels = []
    for v in z:
        if pd.isna(v):
            labels.append("missing")
        elif v <= -1.5:
            labels.append("very_low")
        elif v <= -0.5:
            labels.append("low")
        elif v <= 0.5:
            labels.append("normal_range")
        elif v <= 1.5:
            labels.append("high")
        else:
            labels.append("very_high")
    return pd.Series(labels, index=x.index, dtype="string")


def discretize_continuous(series: pd.Series, scheme_id: str) -> pd.Series:
    if scheme_id == "quantile5_original_10_25_75_90":
        return quantile_label(series, [0.10, 0.25, 0.75, 0.90], ["very_low", "low", "normal_range", "high", "very_high"])
    if scheme_id == "quantile5_wide_normal_05_20_80_95":
        return quantile_label(series, [0.05, 0.20, 0.80, 0.95], ["very_low", "low", "normal_range", "high", "very_high"])
    if scheme_id == "quantile5_narrow_normal_15_30_70_85":
        return quantile_label(series, [0.15, 0.30, 0.70, 0.85], ["very_low", "low", "normal_range", "high", "very_high"])
    if scheme_id == "quantile3_tertiles":
        return qcut_label(series, 3, "q")
    if scheme_id == "quantile4_quartiles":
        return qcut_label(series, 4, "q")
    if scheme_id == "quantile6_sextiles":
        return qcut_label(series, 6, "q")
    if scheme_id == "equal_width5":
        return equal_width_label(series, 5)
    if scheme_id == "zscore5_mean_sd":
        return zscore_label(series)
    raise ValueError(f"Unknown continuous discretization scheme: {scheme_id}")


def infer_assays(raw: pd.DataFrame, discrete: pd.DataFrame, catalog: Optional[pd.DataFrame]) -> List[str]:
    if catalog is not None and "assay" in catalog.columns:
        assays = [str(a) for a in catalog["assay"].dropna().tolist() if str(a) in discrete.columns]
        if assays:
            return assays
    return [c for c in discrete.columns if c not in {"ncu_id", "gene_name", "published_cluster"}]


def infer_continuous_assays(raw: pd.DataFrame, assays: List[str], catalog: Optional[pd.DataFrame]) -> List[str]:
    out = []
    if catalog is not None and {"assay", "assay_type"}.issubset(catalog.columns):
        for _, row in catalog.iterrows():
            assay = str(row["assay"])
            if assay in assays and "continuous" in str(row["assay_type"]).lower():
                out.append(assay)
    if out:
        return out
    for assay in assays:
        numeric = pd.to_numeric(raw[assay], errors="coerce")
        if numeric.notna().sum() >= max(10, int(0.80 * len(raw))) and numeric.nunique(dropna=True) > 8:
            out.append(assay)
    return out


def build_discrete_matrix(raw: pd.DataFrame, baseline: pd.DataFrame, assays: List[str], continuous_assays: List[str], scheme_id: str) -> pd.DataFrame:
    if scheme_id == "baseline_current_file":
        return baseline[["ncu_id", "gene_name"] + assays + ["published_cluster"]].copy()
    out = raw[["ncu_id", "gene_name"]].copy()
    for assay in assays:
        if assay in continuous_assays:
            out[assay] = discretize_continuous(raw[assay], scheme_id)
        else:
            out[assay] = normalize_category(raw[assay])
    out["published_cluster"] = raw["published_cluster"].astype(str)
    return out


def contingency_fast(true: np.ndarray, pred: np.ndarray) -> np.ndarray:
    true = np.asarray(true, dtype=np.int64)
    pred = np.asarray(pred, dtype=np.int64)
    if len(true) == 0:
        return np.zeros((0, 0), dtype=np.int64)
    n_true = int(true.max()) + 1
    n_pred = int(pred.max()) + 1
    return np.bincount(true * n_pred + pred, minlength=n_true * n_pred).reshape(n_true, n_pred)


def metrics_fast(true: np.ndarray, pred: np.ndarray) -> Dict[str, float]:
    cont = contingency_fast(true, pred).astype(float)
    n = float(cont.sum())
    if n <= 1:
        return {"nmi": 0.0, "ari": 0.0, "purity": 1.0}
    row = cont.sum(axis=1)
    col = cont.sum(axis=0)
    nz = cont > 0
    expected = np.outer(row, col)
    mi = float(np.sum((cont[nz] / n) * np.log((cont[nz] * n) / expected[nz])))
    h_true = float(-np.sum((row[row > 0] / n) * np.log(row[row > 0] / n)))
    h_pred = float(-np.sum((col[col > 0] / n) * np.log(col[col > 0] / n)))
    nmi = 2.0 * mi / (h_true + h_pred) if (h_true + h_pred) > 0 else 1.0
    purity = float(cont.max(axis=0).sum() / n) if cont.shape[1] else np.nan
    comb = lambda x: x * (x - 1.0) / 2.0
    sum_comb = float(comb(cont).sum())
    sum_rows = float(comb(row).sum())
    sum_cols = float(comb(col).sum())
    total = float(comb(n))
    if total == 0:
        ari = 0.0
    else:
        expected_index = sum_rows * sum_cols / total
        max_index = 0.5 * (sum_rows + sum_cols)
        denom = max_index - expected_index
        ari = (sum_comb - expected_index) / denom if denom != 0 else 0.0
    return {"nmi": float(nmi), "ari": float(ari), "purity": float(purity)}


class EncodedPhenome:
    def __init__(self, discrete: pd.DataFrame, assays: List[str]):
        self.discrete = discrete.reset_index(drop=True)
        self.assays = list(assays)
        self.m = len(assays)
        self.n = len(discrete)
        self.cluster_codes = pd.factorize(discrete["published_cluster"].astype(str), sort=True)[0]
        code_cols = []
        for assay in assays:
            codes, _ = pd.factorize(discrete[assay].astype(str), sort=True)
            code_cols.append(codes.astype(np.int16))
        self.codes = np.vstack(code_cols).T if code_cols else np.empty((self.n, 0), dtype=np.int16)
        if self.codes.shape[1]:
            self.bases = self.codes.max(axis=0).astype(np.int64) + 1
            self.bases[self.bases < 2] = 2
        else:
            self.bases = np.asarray([], dtype=np.int64)
        self._labels: Dict[int, np.ndarray] = {}
        self._nprofiles: Dict[int, int] = {}

    @property
    def full_mask(self) -> int:
        return (1 << self.m) - 1

    def mask_to_indices(self, mask: int) -> List[int]:
        return [i for i in range(self.m) if mask & (1 << i)]

    def mask_to_assays(self, mask: int) -> List[str]:
        return [self.assays[i] for i in self.mask_to_indices(mask)]

    def labels_for_mask(self, mask: int) -> np.ndarray:
        if mask in self._labels:
            return self._labels[mask]
        idx = self.mask_to_indices(mask)
        if not idx:
            labels = np.zeros(self.n, dtype=np.int32)
        else:
            hashed = np.zeros(self.n, dtype=np.int64)
            for j in idx:
                hashed = hashed * int(self.bases[j]) + self.codes[:, j].astype(np.int64)
            labels = np.unique(hashed, return_inverse=True)[1].astype(np.int32)
        self._labels[mask] = labels
        self._nprofiles[mask] = int(labels.max() + 1) if len(labels) else 0
        return labels

    def n_profiles(self, mask: int) -> int:
        if mask not in self._nprofiles:
            self.labels_for_mask(mask)
        return self._nprofiles[mask]


def all_nonempty_masks(m: int) -> Iterable[int]:
    return range(1, (1 << m))


def subset_metrics(enc: EncodedPhenome) -> Tuple[pd.DataFrame, Dict[str, float]]:
    full_labels = enc.labels_for_mask(enc.full_mask)
    full_profiles = enc.n_profiles(enc.full_mask)
    full_metrics = metrics_fast(enc.cluster_codes, full_labels)
    full_metrics["profiles"] = full_profiles
    rows = []
    for mask in all_nonempty_masks(enc.m):
        labels = enc.labels_for_mask(mask)
        n_profiles = int(np.unique(labels).size)
        met = metrics_fast(enc.cluster_codes, labels)
        rows.append({
            "mask": mask,
            "n_assays": len(enc.mask_to_indices(mask)),
            "assay_set": ";".join(enc.mask_to_assays(mask)),
            "n_profiles": n_profiles,
            "profile_fraction_of_full": n_profiles / full_profiles if full_profiles else np.nan,
            "cluster_nmi": met["nmi"],
            "cluster_ari": met["ari"],
            "cluster_purity": met["purity"],
            "cluster_nmi_fraction_of_full": met["nmi"] / full_metrics["nmi"] if full_metrics["nmi"] > 0 else np.nan,
            "cluster_purity_fraction_of_full": met["purity"] / full_metrics["purity"] if full_metrics["purity"] > 0 else np.nan,
        })
    return pd.DataFrame(rows), full_metrics


def exact_minimal(subsets: pd.DataFrame, full_metrics: Dict[str, float], max_sets: int = 5000) -> Tuple[pd.DataFrame, pd.DataFrame]:
    objectives = [
        ("profile_fraction", "profile_fraction_of_full", 1.0),
        ("cluster_nmi", "cluster_nmi", full_metrics["nmi"]),
        ("cluster_purity", "cluster_purity", full_metrics["purity"]),
    ]
    rows, set_rows = [], []
    for objective, col, full_value in objectives:
        for frac in [0.80, 0.90, 0.95, 0.99, 1.00]:
            target = full_value * frac
            elig = subsets[subsets[col] >= target - 1e-12]
            if elig.empty:
                rows.append({"objective": objective, "target_fraction_of_full": frac, "minimal_n_assays": np.nan, "n_equivalent_minimal_sets": 0})
                continue
            kmin = int(elig["n_assays"].min())
            at = elig[elig["n_assays"] == kmin].sort_values([col, "profile_fraction_of_full"], ascending=False)
            rows.append({
                "objective": objective,
                "target_fraction_of_full": frac,
                "metric_column": col,
                "full_metric_value": full_value,
                "target_metric_value": target,
                "minimal_n_assays": kmin,
                "n_equivalent_minimal_sets": int(len(at)),
                "example_assay_set": at.iloc[0]["assay_set"],
                "best_metric_at_minimal_size": float(at[col].max()),
                "best_profile_fraction_at_minimal_size": float(at["profile_fraction_of_full"].max()),
            })
            for rank, (_, hit) in enumerate(at.head(max_sets).iterrows(), start=1):
                set_rows.append({
                    "objective": objective,
                    "target_fraction_of_full": frac,
                    "rank_within_target": rank,
                    "mask": int(hit["mask"]),
                    "n_assays": int(hit["n_assays"]),
                    "assay_set": hit["assay_set"],
                    "metric_value": float(hit[col]),
                    "profile_fraction_of_full": float(hit["profile_fraction_of_full"]),
                    "cluster_nmi": float(hit["cluster_nmi"]),
                    "cluster_purity": float(hit["cluster_purity"]),
                })
    return pd.DataFrame(rows), pd.DataFrame(set_rows)


def baseline_agreement(baseline_enc: EncodedPhenome, enc: EncodedPhenome, scheme_id: str, full_metrics: Dict[str, float]) -> Dict[str, float | str | int]:
    base_labels = baseline_enc.labels_for_mask(baseline_enc.full_mask)
    labels = enc.labels_for_mask(enc.full_mask)
    met = metrics_fast(base_labels, labels)
    return {
        "scheme_id": scheme_id,
        "baseline_profile_nmi": met["nmi"],
        "baseline_profile_ari": met["ari"],
        "n_full_profiles": enc.n_profiles(enc.full_mask),
        "full_cluster_nmi": full_metrics["nmi"],
        "full_cluster_ari": full_metrics["ari"],
        "full_cluster_purity": full_metrics["purity"],
    }


def run_discretization_sensitivity(raw: pd.DataFrame, baseline: pd.DataFrame, assays: List[str], continuous_assays: List[str]) -> Dict[str, pd.DataFrame]:
    schemes = pd.DataFrame([
        {"scheme_id": "baseline_current_file", "scheme_family": "current", "description": "Current processed matrix generated by scripts/prepare_phenotype_matrix.py"},
        {"scheme_id": "quantile5_original_10_25_75_90", "scheme_family": "quantile", "description": "Five-state quantile binning using 10/25/75/90 percentile cut points"},
        {"scheme_id": "quantile5_wide_normal_05_20_80_95", "scheme_family": "quantile", "description": "Five-state quantile binning with a wider central normal range"},
        {"scheme_id": "quantile5_narrow_normal_15_30_70_85", "scheme_family": "quantile", "description": "Five-state quantile binning with a narrower central normal range"},
        {"scheme_id": "quantile3_tertiles", "scheme_family": "quantile", "description": "Three quantile states"},
        {"scheme_id": "quantile4_quartiles", "scheme_family": "quantile", "description": "Four quantile states"},
        {"scheme_id": "quantile6_sextiles", "scheme_family": "quantile", "description": "Six quantile states"},
        {"scheme_id": "equal_width5", "scheme_family": "equal_width", "description": "Five equal-width bins over the observed range"},
        {"scheme_id": "zscore5_mean_sd", "scheme_family": "zscore", "description": "Five states using mean and standard-deviation thresholds"},
    ])
    baseline_enc = EncodedPhenome(baseline, assays)
    summary_rows, exact_rows, set_rows, best_rows, agreement_rows = [], [], [], [], []
    for _, scheme in schemes.iterrows():
        scheme_id = str(scheme["scheme_id"])
        disc = build_discrete_matrix(raw, baseline, assays, continuous_assays, scheme_id)
        enc = EncodedPhenome(disc, assays)
        subsets, full_metrics = subset_metrics(enc)
        exact, sets = exact_minimal(subsets, full_metrics)
        for frame in [subsets, exact, sets]:
            frame.insert(0, "scheme_id", scheme_id)
        exact_rows.append(exact)
        set_rows.append(sets)
        agreement_rows.append(baseline_agreement(baseline_enc, enc, scheme_id, full_metrics))
        summary_rows.append({
            "scheme_id": scheme_id,
            "n_full_profiles": enc.n_profiles(enc.full_mask),
            "full_cluster_nmi": full_metrics["nmi"],
            "full_cluster_ari": full_metrics["ari"],
            "full_cluster_purity": full_metrics["purity"],
        })
        best = subsets.groupby("n_assays", as_index=False).agg(
            best_profile_fraction=("profile_fraction_of_full", "max"),
            best_cluster_nmi=("cluster_nmi", "max"),
            best_cluster_nmi_fraction=("cluster_nmi_fraction_of_full", "max"),
            best_cluster_purity_fraction=("cluster_purity_fraction_of_full", "max"),
        )
        best.insert(0, "scheme_id", scheme_id)
        best_rows.append(best)
    exact_all = pd.concat(exact_rows, ignore_index=True)
    sets_all = pd.concat(set_rows, ignore_index=True)
    best_all = pd.concat(best_rows, ignore_index=True)
    agreement = pd.DataFrame(agreement_rows)
    assay_inclusion_rows = []
    for objective, target in [("cluster_nmi", 0.95), ("cluster_nmi", 1.0), ("profile_fraction", 0.90), ("profile_fraction", 0.95), ("profile_fraction", 1.0)]:
        sub = sets_all[(sets_all["objective"] == objective) & np.isclose(sets_all["target_fraction_of_full"], target)]
        for scheme_id, g in sub.groupby("scheme_id"):
            total_sets = max(len(g), 1)
            for assay in assays:
                present = g["assay_set"].astype(str).str.split(";").map(lambda vals: assay in vals)
                assay_inclusion_rows.append({
                    "objective": objective,
                    "target_fraction_of_full": target,
                    "scheme_id": scheme_id,
                    "assay": assay,
                    "axis": assay_axis(assay),
                    "inclusion_fraction_within_minimal_sets": float(present.mean()) if len(present) else 0.0,
                    "n_minimal_sets_for_scheme": total_sets,
                })
    inclusion = pd.DataFrame(assay_inclusion_rows)
    if not inclusion.empty:
        scheme_count = inclusion.groupby(["objective", "target_fraction_of_full"])["scheme_id"].nunique().rename("n_schemes")
        agg = inclusion.groupby(["objective", "target_fraction_of_full", "assay", "axis"], as_index=False).agg(
            mean_inclusion_fraction=("inclusion_fraction_within_minimal_sets", "mean"),
            schemes_with_any_inclusion=("inclusion_fraction_within_minimal_sets", lambda x: int((x > 0).sum())),
        )
        agg = agg.merge(scheme_count.reset_index(), on=["objective", "target_fraction_of_full"], how="left")
        agg["scheme_presence_fraction"] = agg["schemes_with_any_inclusion"] / agg["n_schemes"].replace(0, np.nan)
    else:
        agg = pd.DataFrame()
    return {
        "disc_schemes": schemes,
        "disc_summary": pd.DataFrame(summary_rows),
        "disc_baseline_agreement": agreement,
        "disc_exact_minimal": exact_all,
        "disc_minimal_sets": sets_all,
        "disc_best_by_k": best_all,
        "disc_assay_inclusion": inclusion,
        "disc_assay_stability": agg,
    }


def abnormality_table(discrete: pd.DataFrame, assays: List[str]) -> pd.DataFrame:
    out = discrete[["ncu_id", "gene_name", "published_cluster"]].copy()
    for assay in assays:
        out[f"abnormal__{assay}"] = ~discrete[assay].astype(str).str.strip().str.lower().isin(NORMAL_VALUES)
    for axis in ["growth", "asexual_development", "sexual_development"]:
        cols = [f"abnormal__{a}" for a in assays if assay_axis(a) == axis]
        if cols:
            out[f"{axis}_abnormal_any"] = out[cols].any(axis=1)
            out[f"{axis}_abnormal_count"] = out[cols].sum(axis=1).astype(int)
    ab_cols = [f"abnormal__{a}" for a in assays]
    out["total_abnormal_count"] = out[ab_cols].sum(axis=1).astype(int)
    out["any_abnormal"] = out[ab_cols].any(axis=1)
    return out


def parse_sbml_model(root: Path) -> Tuple[pd.DataFrame, set, Optional[Path]]:
    path = find_file(root, [root / "data/raw/dreyfuss_2013/pcbi.1003126.s001.xml"], ["data/raw/dreyfuss_2013/*.xml", "**/pcbi.1003126.s001.xml"])
    if path is None:
        return pd.DataFrame(columns=["ncu_id", "sbml_reaction_count", "sbml_reaction_examples"]), set(), None
    text = path.read_text(encoding="utf-8", errors="ignore")
    genes = {m.group(0).upper() for m in NCU_RE.finditer(text)}
    counts, examples = defaultdict(int), defaultdict(list)
    rxn_pat = re.compile(r"<[^>]*reaction\b.*?</[^>]*reaction>", re.I | re.S)
    id_pat = re.compile(r"\bid=['\"]([^'\"]+)['\"]")
    name_pat = re.compile(r"\bname=['\"]([^'\"]+)['\"]")
    for rxn in rxn_pat.finditer(text):
        block = rxn.group(0)
        rgenes = {m.group(0).upper() for m in NCU_RE.finditer(block)}
        if not rgenes:
            continue
        rid = id_pat.search(block)
        rname = name_pat.search(block)
        label = rid.group(1) if rid else "reaction"
        if rname:
            label = f"{label}:{rname.group(1)}"
        for gene in rgenes:
            counts[gene] += 1
            if len(examples[gene]) < 5:
                examples[gene].append(label)
    df = pd.DataFrame([{"ncu_id": g, "sbml_reaction_count": int(counts.get(g, 0)), "sbml_reaction_examples": ";".join(examples.get(g, []))} for g in sorted(genes)])
    return df, genes, path


def parse_dreyfuss_tables(root: Path) -> pd.DataFrame:
    raw_dir = root / "data/raw/dreyfuss_2013"
    rows = []
    if raw_dir.exists():
        for path in sorted(raw_dir.glob("pcbi.1003126.s00*.xls*")):
            try:
                xl = pd.ExcelFile(path)
            except Exception:
                continue
            for sheet in xl.sheet_names:
                try:
                    df = pd.read_excel(path, sheet_name=sheet, dtype=str)
                except Exception:
                    continue
                text = "\n".join(df.fillna("").astype(str).values.ravel().tolist())
                for gene in sorted({m.group(0).upper() for m in NCU_RE.finditer(text)}):
                    rows.append({"ncu_id": gene, "source_file": path.name, "source_sheet": sheet})
    if not rows:
        return pd.DataFrame(columns=["ncu_id", "mentioned_in_dreyfuss_supp_tables", "dreyfuss_supplementary_annotations"])
    tmp = pd.DataFrame(rows)
    return tmp.groupby("ncu_id", as_index=False).agg(
        mentioned_in_dreyfuss_supp_tables=("source_file", lambda x: True),
        dreyfuss_supplementary_annotations=("source_file", lambda x: ";".join(sorted(set(x)))),
    )


def read_architecture_metabolic_table(root: Path) -> Optional[pd.DataFrame]:
    path = find_file(root, [root / "reports/tables/phenome_architecture_results.xlsx"], ["**/phenome_architecture_results.xlsx"])
    if path is None:
        return None
    try:
        return pd.read_excel(path, sheet_name="metabolic_gene_table")
    except Exception:
        return None


def build_metabolic_sources(root: Path, annot: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    base = annot[["ncu_id", "gene_name"]].copy()
    base["ncu_id"] = base["ncu_id"].astype(str).str.upper()
    base["in_carrillo_metabolic_sheet"] = canonical_bool(annot["is_metabolic_gene_carrillo_sheet"]) if "is_metabolic_gene_carrillo_sheet" in annot.columns else False
    architecture_metabolic = read_architecture_metabolic_table(root)
    if architecture_metabolic is not None and "ncu_id" in architecture_metabolic.columns:
        architecture_metabolic = architecture_metabolic.copy()
        architecture_metabolic["ncu_id"] = architecture_metabolic["ncu_id"].astype(str).str.upper()
        keep = [c for c in ["ncu_id", "sbml_reaction_count", "sbml_reaction_examples", "in_iJDZ836_sbml", "mentioned_in_dreyfuss_supp_tables", "dreyfuss_supplementary_annotations"] if c in architecture_metabolic.columns]
        base = base.merge(architecture_metabolic[keep].drop_duplicates("ncu_id"), on="ncu_id", how="left")
    else:
        sbml_df, sbml_genes, _ = parse_sbml_model(root)
        if not sbml_df.empty:
            base = base.merge(sbml_df, on="ncu_id", how="left")
        else:
            base["sbml_reaction_count"] = 0
            base["sbml_reaction_examples"] = ""
        base["in_iJDZ836_sbml"] = base["ncu_id"].isin(sbml_genes)
        mentions = parse_dreyfuss_tables(root)
        base = base.merge(mentions, on="ncu_id", how="left")
    for col in ["in_iJDZ836_sbml", "mentioned_in_dreyfuss_supp_tables"]:
        if col not in base.columns:
            base[col] = False
        base[col] = canonical_bool(base[col])
    if "sbml_reaction_count" not in base.columns:
        base["sbml_reaction_count"] = 0
    base["sbml_reaction_count"] = pd.to_numeric(base["sbml_reaction_count"], errors="coerce").fillna(0).astype(int)
    for col in ["sbml_reaction_examples", "dreyfuss_supplementary_annotations"]:
        if col not in base.columns:
            base[col] = ""
        base[col] = base[col].fillna("").astype(str)
    source_cols = ["in_carrillo_metabolic_sheet", "in_iJDZ836_sbml", "mentioned_in_dreyfuss_supp_tables"]
    base["n_metabolic_definitions"] = base[source_cols].astype(bool).sum(axis=1)
    base["metabolic_any"] = base["n_metabolic_definitions"] >= 1
    base["metabolic_high_confidence"] = base["n_metabolic_definitions"] >= 2
    base["metabolic_consensus_3definitions"] = base["n_metabolic_definitions"] >= 3
    base["sbml_only"] = base["in_iJDZ836_sbml"] & ~base["in_carrillo_metabolic_sheet"] & ~base["mentioned_in_dreyfuss_supp_tables"]
    base["carrillo_only"] = base["in_carrillo_metabolic_sheet"] & ~base["in_iJDZ836_sbml"] & ~base["mentioned_in_dreyfuss_supp_tables"]
    base["dreyfuss_table_only"] = base["mentioned_in_dreyfuss_supp_tables"] & ~base["in_iJDZ836_sbml"] & ~base["in_carrillo_metabolic_sheet"]
    coverage = []
    n_total = len(base)
    for col in source_cols + ["metabolic_any", "metabolic_high_confidence", "metabolic_consensus_3definitions", "sbml_only", "carrillo_only", "dreyfuss_table_only"]:
        coverage.append({"metabolic_definition": col, "n_genes_in_phenome": int(base[col].fillna(False).astype(bool).sum()), "fraction_of_phenome": float(base[col].fillna(False).astype(bool).mean()), "n_total_genes": n_total})
    return base, pd.DataFrame(coverage)


def keyword_series(annot: pd.DataFrame) -> Tuple[pd.Series, pd.Series, pd.Series]:
    cls = annot.get("gene_classification", pd.Series([""] * len(annot))).fillna("").astype(str).str.upper()
    desc = annot.get("product_description", pd.Series([""] * len(annot))).fillna("").astype(str).str.lower()
    gene = annot.get("gene_name", pd.Series([""] * len(annot))).fillna("").astype(str).str.lower()
    return cls, desc, gene


def build_gene_class_modes(annot: pd.DataFrame, metabolic: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    cls, desc, gene = keyword_series(annot)
    tm = pd.to_numeric(annot.get("n_transmembrane_helices", pd.Series([0] * len(annot))), errors="coerce").fillna(0)
    ph = pd.to_numeric(annot.get("n_phosphorylation_sites", pd.Series([0] * len(annot))), errors="coerce")
    ph_cut = ph.dropna().quantile(0.75) if ph.notna().any() else np.inf
    base = annot[["ncu_id", "gene_name"]].copy()
    base["ncu_id"] = base["ncu_id"].astype(str).str.upper()
    metab = metabolic.drop(columns=["gene_name"], errors="ignore")
    base = base.merge(metab, on="ncu_id", how="left")
    for col in ["in_carrillo_metabolic_sheet", "in_iJDZ836_sbml", "mentioned_in_dreyfuss_supp_tables", "metabolic_any", "metabolic_high_confidence"]:
        if col not in base.columns:
            base[col] = False
        base[col] = canonical_bool(base[col])
    if "has_yeast_ortholog" in annot.columns:
        yeast = canonical_bool(annot["has_yeast_ortholog"])
    else:
        yeast = pd.Series([False] * len(annot), index=annot.index)
    common = {
        "yeast_ortholog": yeast,
        "no_yeast_ortholog": ~yeast,
        "transmembrane_any": tm >= 1,
        "transmembrane_5plus": tm >= 5,
        "high_phosphorylation_q75": ph.fillna(0) >= ph_cut,
        "metabolic_iJDZ836_sbml": base["in_iJDZ836_sbml"],
        "metabolic_carrillo_sheet": base["in_carrillo_metabolic_sheet"],
        "metabolic_any": base["metabolic_any"],
        "metabolic_high_confidence": base["metabolic_high_confidence"],
    }
    strict = {
        "TF": cls.eq("TF"),
        "GPCR": cls.eq("GPCR"),
        "ser_thr_kinase": cls.eq("STKIN"),
        "phosphatase": cls.eq("PASE"),
    }
    default = {
        "TF": strict["TF"] | desc.str.contains("transcription factor|zn2cys6|c2h2|bzip|myb|homeobox|ap2", regex=True),
        "GPCR": strict["GPCR"] | desc.str.contains("g-protein-coupled|gpcr", regex=True) | gene.str.match(r"gpr-"),
        "ser_thr_kinase": strict["ser_thr_kinase"] | desc.str.contains("serine/threonine|protein kinase|map kinase|kinase", regex=True),
        "phosphatase": strict["phosphatase"] | desc.str.contains("phosphatase", regex=True),
    }
    broad = {
        "TF": default["TF"] | desc.str.contains("dna-binding|zinc finger|helix-turn-helix|regulator", regex=True),
        "GPCR": default["GPCR"] | ((tm >= 6) & desc.str.contains("receptor|membrane|signal", regex=True)),
        "ser_thr_kinase": default["ser_thr_kinase"] | desc.str.contains("phosphotransferase|kinase domain", regex=True),
        "phosphatase": default["phosphatase"] | desc.str.contains("pp2c|protein phosphatase|phosphoprotein phosphatase", regex=True),
    }
    rows = []
    for mode, mode_dict in [("strict", strict), ("default", default), ("broad", broad)]:
        frame = annot[["ncu_id", "gene_name"]].copy()
        frame["mode"] = mode
        for col, ser in {**common, **mode_dict}.items():
            frame[col] = ser.fillna(False).astype(bool).to_numpy()
        rows.append(frame)
    rule_rows = [
        {"mode": "strict", "gene_class": "TF", "rule_description": "Gene Classification equals TF", "source_columns": "gene_classification"},
        {"mode": "strict", "gene_class": "GPCR", "rule_description": "Gene Classification equals GPCR", "source_columns": "gene_classification"},
        {"mode": "strict", "gene_class": "ser_thr_kinase", "rule_description": "Gene Classification equals STKIN", "source_columns": "gene_classification"},
        {"mode": "strict", "gene_class": "phosphatase", "rule_description": "Gene Classification equals PASE", "source_columns": "gene_classification"},
        {"mode": "default", "gene_class": "TF", "rule_description": "Strict TF plus common transcription-factor keywords", "source_columns": "gene_classification;product_description"},
        {"mode": "default", "gene_class": "GPCR", "rule_description": "Strict GPCR plus GPCR/G-protein-coupled keywords and gpr-* names", "source_columns": "gene_classification;product_description;gene_name"},
        {"mode": "default", "gene_class": "ser_thr_kinase", "rule_description": "Strict STKIN plus kinase-related product-description keywords", "source_columns": "gene_classification;product_description"},
        {"mode": "default", "gene_class": "phosphatase", "rule_description": "Strict PASE plus phosphatase product-description keyword", "source_columns": "gene_classification;product_description"},
        {"mode": "broad", "gene_class": "TF", "rule_description": "Default TF plus broader DNA-binding/regulator keywords", "source_columns": "gene_classification;product_description"},
        {"mode": "broad", "gene_class": "GPCR", "rule_description": "Default GPCR plus receptor-like multi-pass transmembrane heuristic", "source_columns": "gene_classification;product_description;n_transmembrane_helices"},
        {"mode": "broad", "gene_class": "ser_thr_kinase", "rule_description": "Default kinase plus broader kinase-domain terms", "source_columns": "gene_classification;product_description"},
        {"mode": "broad", "gene_class": "phosphatase", "rule_description": "Default phosphatase plus PP2C/protein-phosphatase terms", "source_columns": "gene_classification;product_description"},
        {"mode": "all", "gene_class": "metabolic_any", "rule_description": "Union of Carrillo metabolic sheet, iJDZ836 SBML membership, and Dreyfuss supplementary-table mentions", "source_columns": "Carrillo Additional file 1;Dreyfuss SBML;Dreyfuss supplementary tables"},
        {"mode": "all", "gene_class": "metabolic_high_confidence", "rule_description": "Present in at least two metabolic sources", "source_columns": "Carrillo Additional file 1;Dreyfuss SBML;Dreyfuss supplementary tables"},
    ]
    return pd.concat(rows, ignore_index=True), pd.DataFrame(rule_rows)


def gene_class_counts(modes: pd.DataFrame, min_class_size: int) -> pd.DataFrame:
    class_cols = [c for c in modes.columns if c not in {"ncu_id", "gene_name", "mode"}]
    rows = []
    for mode, group in modes.groupby("mode"):
        for col in class_cols:
            n = int(group[col].fillna(False).astype(bool).sum())
            rows.append({"mode": mode, "gene_class": col, "n_genes": n, "fraction_of_phenome": n / len(group), "passes_min_class_size": n >= min_class_size})
    return pd.DataFrame(rows)


def gene_class_overlap(modes: pd.DataFrame) -> pd.DataFrame:
    class_cols = [c for c in modes.columns if c not in {"ncu_id", "gene_name", "mode"}]
    rows = []
    for mode, group in modes.groupby("mode"):
        for a, b in itertools.combinations(class_cols, 2):
            x = group[a].fillna(False).astype(bool).to_numpy()
            y = group[b].fillna(False).astype(bool).to_numpy()
            both = int((x & y).sum())
            union = int((x | y).sum())
            # Phi coefficient for binary overlap.
            table = np.array([[both, int((x & ~y).sum())], [int((~x & y).sum()), int((~x & ~y).sum())]], dtype=float)
            denom = math.sqrt(table.sum(axis=0).prod() * table.sum(axis=1).prod())
            phi = ((table[0, 0] * table[1, 1]) - (table[0, 1] * table[1, 0])) / denom if denom else np.nan
            rows.append({"mode": mode, "class_a": a, "class_b": b, "n_a": int(x.sum()), "n_b": int(y.sum()), "n_both": both, "jaccard": both / union if union else np.nan, "phi": phi})
    return pd.DataFrame(rows)


def gene_definition_breakdown(annot: pd.DataFrame, modes: pd.DataFrame) -> pd.DataFrame:
    strict = modes[modes["mode"] == "strict"].set_index("ncu_id")
    default = modes[modes["mode"] == "default"].set_index("ncu_id")
    broad = modes[modes["mode"] == "broad"].set_index("ncu_id")
    rows = []
    for cls_name in ["TF", "GPCR", "ser_thr_kinase", "phosphatase"]:
        s = strict[cls_name].astype(bool)
        d = default[cls_name].astype(bool)
        b = broad[cls_name].astype(bool)
        rows.append({"gene_class": cls_name, "strict_n": int(s.sum()), "default_n": int(d.sum()), "broad_n": int(b.sum()),
                     "default_added_by_keyword": int((d & ~s).sum()), "broad_added_beyond_default": int((b & ~d).sum()),
                     "strict_fraction_of_default": int(s.sum()) / max(int(d.sum()), 1), "default_fraction_of_broad": int(d.sum()) / max(int(b.sum()), 1)})
    missing_product = int(annot.get("product_description", pd.Series([np.nan] * len(annot))).isna().sum())
    rows.append({"gene_class": "annotation_missingness", "strict_n": missing_product, "default_n": np.nan, "broad_n": np.nan,
                 "default_added_by_keyword": np.nan, "broad_added_beyond_default": np.nan, "strict_fraction_of_default": np.nan,
                 "default_fraction_of_broad": np.nan, "note": "strict_n stores number of genes missing product_description"})
    return pd.DataFrame(rows)


def enrichment_by_mode(modes: pd.DataFrame, abnormal: pd.DataFrame, min_class_size: int) -> pd.DataFrame:
    rows = []
    axes = ["growth", "asexual_development", "sexual_development"]
    class_cols = [c for c in modes.columns if c not in {"ncu_id", "gene_name", "mode"}]
    for mode, group in modes.groupby("mode"):
        data = abnormal.merge(group, on=["ncu_id", "gene_name"], how="inner")
        for gene_class in class_cols:
            mem = data[gene_class].fillna(False).astype(bool)
            if mem.sum() < min_class_size or (~mem).sum() < min_class_size:
                continue
            for axis in axes:
                col = f"{axis}_abnormal_any"
                if col not in data.columns:
                    continue
                ab = data[col].astype(bool)
                x1, x0 = int((mem & ab).sum()), int((mem & ~ab).sum())
                y1, y0 = int((~mem & ab).sum()), int((~mem & ~ab).sum())
                odds, p = safe_fisher(x1, x0, y1, y0)
                rows.append({"mode": mode, "gene_class": gene_class, "axis": axis, "n_class_genes": int(mem.sum()),
                             "class_abnormal": x1, "class_normal": x0, "nonclass_abnormal": y1, "nonclass_normal": y0,
                             "abnormal_rate_class": x1 / max(x1 + x0, 1), "abnormal_rate_nonclass": y1 / max(y1 + y0, 1),
                             "odds_ratio": odds, "log2_odds_ratio_corrected": log2_or_corrected(x1, x0, y1, y0), "fisher_p": p})
    out = pd.DataFrame(rows)
    if not out.empty:
        out["fdr_q"] = bh_fdr(out["fisher_p"])
    return out


def mode_stability(enrich: pd.DataFrame) -> pd.DataFrame:
    if enrich.empty:
        return pd.DataFrame()
    rows = []
    for (gene_class, axis), group in enrich.groupby(["gene_class", "axis"]):
        vals = group.set_index("mode")
        signs = np.sign(vals["log2_odds_ratio_corrected"].fillna(0).to_numpy())
        nonzero = signs[signs != 0]
        sign_consistent = bool(len(nonzero) > 0 and np.all(nonzero == nonzero[0]))
        rows.append({
            "gene_class": gene_class,
            "axis": axis,
            "n_modes_tested": int(vals.shape[0]),
            "sign_consistent_across_modes": sign_consistent,
            "n_modes_fdr_lt_0_05": int((vals["fdr_q"] < 0.05).sum()),
            "min_fdr_q": float(vals["fdr_q"].min()),
            "max_fdr_q": float(vals["fdr_q"].max()),
            "strict_log2_or": float(vals.loc["strict", "log2_odds_ratio_corrected"]) if "strict" in vals.index else np.nan,
            "default_log2_or": float(vals.loc["default", "log2_odds_ratio_corrected"]) if "default" in vals.index else np.nan,
            "broad_log2_or": float(vals.loc["broad", "log2_odds_ratio_corrected"]) if "broad" in vals.index else np.nan,
            "interpretation_flag": "robust" if sign_consistent and int((vals["fdr_q"] < 0.05).sum()) >= 2 else "definition_sensitive",
        })
    return pd.DataFrame(rows).sort_values(["interpretation_flag", "min_fdr_q", "gene_class", "axis"])


def metabolic_axis_enrichment(metabolic: pd.DataFrame, abnormal: pd.DataFrame, min_class_size: int) -> pd.DataFrame:
    definitions = ["in_iJDZ836_sbml", "in_carrillo_metabolic_sheet", "mentioned_in_dreyfuss_supp_tables", "metabolic_any", "metabolic_high_confidence", "metabolic_consensus_3definitions"]
    data = abnormal.merge(metabolic, on=["ncu_id", "gene_name"], how="left")
    rows = []
    for definition in definitions:
        if definition not in data.columns:
            continue
        mem = data[definition].fillna(False).astype(bool)
        if mem.sum() < min_class_size or (~mem).sum() < min_class_size:
            continue
        for axis in ["growth", "asexual_development", "sexual_development"]:
            col = f"{axis}_abnormal_any"
            if col not in data.columns:
                continue
            ab = data[col].astype(bool)
            x1, x0 = int((mem & ab).sum()), int((mem & ~ab).sum())
            y1, y0 = int((~mem & ab).sum()), int((~mem & ~ab).sum())
            odds, p = safe_fisher(x1, x0, y1, y0)
            rows.append({"metabolic_definition": definition, "axis": axis, "n_metabolic_genes": int(mem.sum()), "metabolic_abnormal": x1,
                         "metabolic_normal": x0, "nonmetabolic_abnormal": y1, "nonmetabolic_normal": y0,
                         "abnormal_rate_metabolic": x1 / max(x1 + x0, 1), "abnormal_rate_nonmetabolic": y1 / max(y1 + y0, 1),
                         "odds_ratio": odds, "log2_odds_ratio_corrected": log2_or_corrected(x1, x0, y1, y0), "fisher_p": p})
    out = pd.DataFrame(rows)
    if not out.empty:
        out["fdr_q"] = bh_fdr(out["fisher_p"])
    return out


def metabolic_bias_scores(axis_enrich: pd.DataFrame) -> pd.DataFrame:
    rows = []
    if axis_enrich.empty:
        return pd.DataFrame()
    for definition, group in axis_enrich.groupby("metabolic_definition"):
        vals = group.set_index("axis")["log2_odds_ratio_corrected"].to_dict()
        growth = vals.get("growth", np.nan)
        dev = np.nanmean([vals.get("asexual_development", np.nan), vals.get("sexual_development", np.nan)])
        rows.append({"metabolic_definition": definition, "growth_log2_or": growth, "mean_development_log2_or": dev,
                     "growth_minus_development_bias": growth - dev if np.isfinite(growth) and np.isfinite(dev) else np.nan,
                     "supports_growth_dominance": bool(np.isfinite(growth) and growth > 0 and growth > dev)})
    return pd.DataFrame(rows)


def random_set_bias_null(metabolic: pd.DataFrame, abnormal: pd.DataFrame, axis_enrich: pd.DataFrame, iterations: int, rng: np.random.Generator, min_class_size: int) -> Tuple[pd.DataFrame, pd.DataFrame]:
    data = abnormal.merge(metabolic, on=["ncu_id", "gene_name"], how="left")
    axes = ["growth", "asexual_development", "sexual_development"]
    axis_arrays = {axis: data[f"{axis}_abnormal_any"].fillna(False).astype(bool).to_numpy() for axis in axes if f"{axis}_abnormal_any" in data.columns}
    n = len(data)
    obs_bias = metabolic_bias_scores(axis_enrich).set_index("metabolic_definition")
    summary_rows, iter_rows = [], []
    for definition in ["in_iJDZ836_sbml", "in_carrillo_metabolic_sheet", "mentioned_in_dreyfuss_supp_tables", "metabolic_any", "metabolic_high_confidence"]:
        if definition not in data.columns or definition not in obs_bias.index:
            continue
        mem = data[definition].fillna(False).astype(bool).to_numpy()
        k = int(mem.sum())
        if k < min_class_size or n - k < min_class_size:
            continue
        null_biases = []
        for it in range(iterations):
            idx = rng.choice(n, size=k, replace=False)
            rand = np.zeros(n, dtype=bool)
            rand[idx] = True
            log2s = {}
            for axis, ab in axis_arrays.items():
                x1, x0 = int((rand & ab).sum()), int((rand & ~ab).sum())
                y1, y0 = int((~rand & ab).sum()), int((~rand & ~ab).sum())
                log2s[axis] = log2_or_corrected(x1, x0, y1, y0)
            dev = np.nanmean([log2s.get("asexual_development", np.nan), log2s.get("sexual_development", np.nan)])
            bias = log2s.get("growth", np.nan) - dev
            null_biases.append(bias)
            iter_rows.append({"metabolic_definition": definition, "iteration": it + 1, "random_growth_minus_development_bias": bias})
        vals = np.asarray(null_biases, dtype=float)
        obs = float(obs_bias.loc[definition, "growth_minus_development_bias"])
        summary_rows.append({"metabolic_definition": definition, "n_metabolic_genes": k, "observed_growth_minus_development_bias": obs,
                             "null_mean_bias": float(np.nanmean(vals)), "null_sd_bias": float(np.nanstd(vals, ddof=1)),
                             "empirical_p_random_ge_observed": (np.sum(vals >= obs) + 1) / (len(vals) + 1),
                             "empirical_p_random_le_observed": (np.sum(vals <= obs) + 1) / (len(vals) + 1),
                             "observed_percentile_in_random_sets": float(np.mean(vals <= obs)), "random_set_iterations": int(len(vals))})
    return pd.DataFrame(summary_rows), pd.DataFrame(iter_rows)


def reaction_count_correlations(metabolic: pd.DataFrame, abnormal: pd.DataFrame) -> pd.DataFrame:
    data = abnormal.merge(metabolic, on=["ncu_id", "gene_name"], how="left")
    model = data[data.get("in_iJDZ836_sbml", pd.Series(False, index=data.index)).fillna(False).astype(bool)].copy()
    if model.empty or "sbml_reaction_count" not in model.columns:
        return pd.DataFrame()
    rows = []
    for col in ["growth_abnormal_count", "asexual_development_abnormal_count", "sexual_development_abnormal_count", "total_abnormal_count"]:
        if col not in model.columns or model["sbml_reaction_count"].nunique() <= 1:
            continue
        rho, p = stats.spearmanr(model["sbml_reaction_count"], model[col])
        rows.append({"x": "sbml_reaction_count", "y": col, "n_model_genes_in_phenome": int(len(model)), "spearman_rho": rho, "spearman_p": p})
    out = pd.DataFrame(rows)
    if not out.empty:
        out["fdr_q"] = bh_fdr(out["spearman_p"])
    return out


def build_metabolic_bias_summary(axis_enrich: pd.DataFrame, bias: pd.DataFrame, random_summary: pd.DataFrame, coverage: pd.DataFrame) -> pd.DataFrame:
    rows = []
    bias_any = bias[bias["metabolic_definition"] == "metabolic_any"] if not bias.empty else pd.DataFrame()
    growth_bias = float(bias_any["growth_minus_development_bias"].iloc[0]) if not bias_any.empty else np.nan
    growth_log2 = float(bias_any["growth_log2_or"].iloc[0]) if not bias_any.empty else np.nan
    rows.append({
        "interpretation": "Dominant metabolic growth-axis interpretation",
        "support_status": "not_supported_by_enrichment_results" if (not np.isfinite(growth_bias) or growth_bias <= 0 or growth_log2 <= 0) else "partly_supported",
        "evidence_evaluated": "metabolic_any growth log2 OR and growth-minus-development bias",
        "observed_result": f"growth_log2_or={growth_log2:.3g}; growth_minus_development={growth_bias:.3g}" if np.isfinite(growth_bias) else "not available",
        "suggested_interpretation": "Metabolic membership is best treated as a historical contrast layer rather than as evidence that metabolic genes dominate growth-axis phenotypes.",
    })
    cov_any = coverage[coverage["metabolic_definition"] == "metabolic_any"]
    rows.append({
        "interpretation": "Metabolic model as historical contrast layer",
        "support_status": "supported_as_contextual_layer",
        "evidence_evaluated": "metabolic gene-set definition coverage and axis enrichment table",
        "observed_result": f"metabolic_any genes in phenome={int(cov_any['n_genes_in_phenome'].iloc[0])}" if not cov_any.empty else "not available",
        "suggested_interpretation": "The iJDZ836/Carrillo metabolic layer provides a historical Beadle/Srb contrast, but the deletion phenome is not reducible to metabolic-model membership alone.",
    })
    rows.append({
        "interpretation": "Developmental-axis information beyond growth readout",
        "support_status": "supported_by_sensitivity_analyses",
        "evidence_evaluated": "cluster recovery, assay Shapley, gene-class axis enrichment, and metabolic contrast",
        "observed_result": "see sensitivity and analysis workbooks",
        "suggested_interpretation": "Classical Neurospora phenotyping preserves a growth-associated historical signal while developmental assays encode additional filamentous-fungal functional structure.",
    })
    return pd.DataFrame(rows)


def write_workbook(path: Path, sheets: Dict[str, pd.DataFrame]) -> None:
    ensure_dir(path.parent)
    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        for name, df in sheets.items():
            frame = df if df is not None else pd.DataFrame()
            frame.to_excel(writer, sheet_name=name[:31], index=False)
            ws = writer.book[name[:31]]
            ws.freeze_panes = "A2"
            for i, col in enumerate(frame.columns, start=1):
                values = frame[col].head(250).fillna("").astype(str).tolist() if len(frame) else []
                width = min(max([len(str(col))] + [len(v) for v in values]) + 2, 45)
                ws.column_dimensions[ws.cell(1, i).column_letter].width = max(width, 10)
            for cell in ws[1]:
                cell.style = "Headline 4"


def main() -> None:
    args = parse_args()
    root = Path(args.project_root).expanduser().resolve()
    processed = root / "data" / "processed"
    tables = ensure_dir(root / "reports" / "tables")
    source = ensure_dir(root / "reports" / "source_data" / "sensitivity")

    raw = read_csv_required(find_file(root, [processed / "phenotype_matrix_raw.csv", root / "phenotype_matrix_raw.csv"], ["**/phenotype_matrix_raw.csv"]), "phenotype_matrix_raw.csv")
    baseline = read_csv_required(find_file(root, [processed / "phenotype_matrix_discrete.csv", root / "phenotype_matrix_discrete.csv"], ["**/phenotype_matrix_discrete.csv"]), "phenotype_matrix_discrete.csv")
    annot = read_csv_required(find_file(root, [processed / "gene_annotations.csv", root / "gene_annotations.csv"], ["**/gene_annotations.csv"]), "gene_annotations.csv")
    catalog_path = find_file(root, [processed / "assay_catalog.csv", root / "assay_catalog.csv"], ["**/assay_catalog.csv"])
    catalog = pd.read_csv(catalog_path) if catalog_path else None
    assays = infer_assays(raw, baseline, catalog)
    continuous_assays = infer_continuous_assays(raw, assays, catalog)
    if not continuous_assays:
        raise ValueError("No continuous assays were detected; discretization sensitivity cannot be evaluated.")

    sensitivity = run_discretization_sensitivity(raw, baseline, assays, continuous_assays)
    abnormal = abnormality_table(baseline, assays)
    metabolic, metabolic_coverage = build_metabolic_sources(root, annot)
    modes, rulebook = build_gene_class_modes(annot, metabolic)
    counts = gene_class_counts(modes, args.min_class_size)
    overlaps = gene_class_overlap(modes)
    definition_breakdown = gene_definition_breakdown(annot, modes)
    enrich_modes = enrichment_by_mode(modes, abnormal, args.min_class_size)
    stability = mode_stability(enrich_modes)
    met_axis = metabolic_axis_enrichment(metabolic, abnormal, args.min_class_size)
    met_bias = metabolic_bias_scores(met_axis)
    rand_summary, rand_iters = random_set_bias_null(metabolic, abnormal, met_axis, args.random_set_iterations, np.random.default_rng(args.random_seed + 5), args.min_class_size)
    rxn_corr = reaction_count_correlations(metabolic, abnormal)
    metabolic_summary = build_metabolic_bias_summary(met_axis, met_bias, rand_summary, metabolic_coverage)

    summary = pd.DataFrame([{
        "n_mutants": len(baseline),
        "n_assays": len(assays),
        "continuous_assays_tested": ";".join(continuous_assays),
        "n_discretization_schemes": int(len(sensitivity["disc_schemes"])),
        "n_gene_class_modes": int(modes["mode"].nunique()),
        "random_set_iterations": args.random_set_iterations,
        "min_class_size": args.min_class_size,
        "random_seed": args.random_seed,
    }])

    sheets: Dict[str, pd.DataFrame] = {
        "summary_sensitivity": summary,
        **sensitivity,
        "gene_class_rulebook": rulebook,
        "gene_class_counts": counts,
        "gene_class_overlap": overlaps,
        "gene_class_definition_breakdown": definition_breakdown,
        "gene_class_axis_enrich_modes": enrich_modes.sort_values("fdr_q") if not enrich_modes.empty else enrich_modes,
        "gene_class_mode_stability": stability,
        "metabolic_definition_table": metabolic,
        "metabolic_definition_coverage": metabolic_coverage,
        "metabolic_axis_enrichment": met_axis.sort_values("fdr_q") if not met_axis.empty else met_axis,
        "metabolic_bias_scores": met_bias,
        "metabolic_random_set_summary": rand_summary,
        "metabolic_random_set_iters": rand_iters,
        "metabolic_reaction_count_corr": rxn_corr,
        "metabolic_bias_summary": metabolic_summary,
        "abnormality_table": abnormal,
    }
    out = Path(args.output_workbook) if args.output_workbook else tables / "phenome_sensitivity_results.xlsx"
    write_workbook(out, sheets)

    for name, df in sheets.items():
        if name in {"abnormality_table", "metabolic_random_set_iters"}:
            continue
        df.to_csv(source / f"{name}.csv", index=False)

    print(f"Sensitivity analysis complete: {out}")
    print(summary.to_string(index=False))
    key = sensitivity["disc_exact_minimal"]
    key = key[(key["objective"].isin(["profile_fraction", "cluster_nmi"])) & (key["target_fraction_of_full"].isin([0.90, 0.95, 1.00]))]
    if not key.empty:
        print("\nDiscretization sensitivity key minimal sizes:")
        print(key[["scheme_id", "objective", "target_fraction_of_full", "minimal_n_assays", "example_assay_set"]].to_string(index=False))
    print("\nMetabolic bias summary:")
    print(metabolic_summary[["interpretation", "support_status", "observed_result"]].to_string(index=False))


if __name__ == "__main__":
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=FutureWarning)
        main()
